title: My Blog
email: your-email@example.com
description: >- 
  A beautiful Jekyll blog with pagination.
baseurl: "/mmblog"
url: "https://thuhoai27.github.io"
twitter_username: jekyllrb
github_username: thuhoai27

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 3
paginate_path: "/mmblog/page/:num/"